// Generated by gencpp from file rslidar_msgs/rslidarPic.msg
// DO NOT EDIT!


#ifndef RSLIDAR_MSGS_MESSAGE_RSLIDARPIC_H
#define RSLIDAR_MSGS_MESSAGE_RSLIDARPIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rslidar_msgs
{
template <class ContainerAllocator>
struct rslidarPic_
{
  typedef rslidarPic_<ContainerAllocator> Type;

  rslidarPic_()
    : header()
    , col(0)
    , distance()
    , intensity()
    , azimuthforeachP()  {
    }
  rslidarPic_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , col(0)
    , distance(_alloc)
    , intensity(_alloc)
    , azimuthforeachP(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _col_type;
  _col_type col;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _distance_type;
  _distance_type distance;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _intensity_type;
  _intensity_type intensity;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _azimuthforeachP_type;
  _azimuthforeachP_type azimuthforeachP;





  typedef boost::shared_ptr< ::rslidar_msgs::rslidarPic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rslidar_msgs::rslidarPic_<ContainerAllocator> const> ConstPtr;

}; // struct rslidarPic_

typedef ::rslidar_msgs::rslidarPic_<std::allocator<void> > rslidarPic;

typedef boost::shared_ptr< ::rslidar_msgs::rslidarPic > rslidarPicPtr;
typedef boost::shared_ptr< ::rslidar_msgs::rslidarPic const> rslidarPicConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rslidar_msgs::rslidarPic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rslidar_msgs::rslidarPic_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rslidar_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rslidar_msgs': ['/home/pc/catkin_ws/src/rslidar/rslidar_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rslidar_msgs::rslidarPic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rslidar_msgs::rslidarPic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rslidar_msgs::rslidarPic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rslidar_msgs::rslidarPic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rslidar_msgs::rslidarPic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rslidar_msgs::rslidarPic_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rslidar_msgs::rslidarPic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6082ae0a03112c5dd200b5cae6f683d";
  }

  static const char* value(const ::rslidar_msgs::rslidarPic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6082ae0a03112c5ULL;
  static const uint64_t static_value2 = 0xdd200b5cae6f683dULL;
};

template<class ContainerAllocator>
struct DataType< ::rslidar_msgs::rslidarPic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rslidar_msgs/rslidarPic";
  }

  static const char* value(const ::rslidar_msgs::rslidarPic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rslidar_msgs::rslidarPic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header		    header\n\
uint32               col\n\
float32[]           distance\n\
float32[]           intensity\n\
float32[]           azimuthforeachP\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::rslidar_msgs::rslidarPic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rslidar_msgs::rslidarPic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.col);
      stream.next(m.distance);
      stream.next(m.intensity);
      stream.next(m.azimuthforeachP);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rslidarPic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rslidar_msgs::rslidarPic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rslidar_msgs::rslidarPic_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "col: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.col);
    s << indent << "distance[]" << std::endl;
    for (size_t i = 0; i < v.distance.size(); ++i)
    {
      s << indent << "  distance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distance[i]);
    }
    s << indent << "intensity[]" << std::endl;
    for (size_t i = 0; i < v.intensity.size(); ++i)
    {
      s << indent << "  intensity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.intensity[i]);
    }
    s << indent << "azimuthforeachP[]" << std::endl;
    for (size_t i = 0; i < v.azimuthforeachP.size(); ++i)
    {
      s << indent << "  azimuthforeachP[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.azimuthforeachP[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSLIDAR_MSGS_MESSAGE_RSLIDARPIC_H
